import type { Rutina } from "@/types"

export const ROUTINE_RESOURCE_MAP: Record<string, Rutina> = {
  "guia-fullbody-3-dias": {
    id: "pdf-masa-principiante-fullbody-3d",
    slug: "masa-principiante-fullbody-3d",
    title: "Full Body Base para Masa (3 días)",
    short_description: "Rutina inicial con ejercicios compuestos para construir masa muscular y técnica.",
    level_label: "Principiante",
    objetivo: "ganar_masa_muscular",
    experiencia: "principiante",
    dias_por_semana: 3,
    duracion_semanas: 8,
    estimated_session_minutes: 60,
    focus_areas: ["hipertrofia inicial", "técnica de fuerza", "consistencia semanal"],
    dias: [
      {
        dia: "dia_1",
        nombre_dia: "Día 1 · Full Body A",
        enfoque: "Fuerza general de cuerpo completo",
        musculo: "Cuerpo completo",
        notas: "Prioriza sentadilla, empuje horizontal, tracción y bisagra de cadera.",
        ejercicios: [
          { nombre: "Sentadilla goblet o trasera", series: 3, repeticiones: "6-10 rep", descanso: "90-120 s", notas: "Tronco firme y bajada controlada." },
          { nombre: "Press de banca o mancuernas", series: 3, repeticiones: "6-10 rep", descanso: "90 s", notas: "Escápulas activas y recorrido completo." },
          { nombre: "Remo con mancuerna o polea", series: 3, repeticiones: "8-12 rep", descanso: "75-90 s", notas: "Inicia el tirón con espalda." },
          { nombre: "Peso muerto rumano", series: 3, repeticiones: "8-10 rep", descanso: "90 s", notas: "Bisagra limpia, columna neutra." },
        ],
      },
      {
        dia: "dia_2",
        nombre_dia: "Día 2 · Full Body B",
        enfoque: "Torso mixto con volumen moderado",
        musculo: "Torso",
        notas: "Suma repeticiones antes de subir carga en accesorios.",
        ejercicios: [
          { nombre: "Press inclinado en máquina", series: 3, repeticiones: "10-12 rep", descanso: "75 s", notas: "Excéntrica de 2 segundos." },
          { nombre: "Remo pecho apoyado", series: 3, repeticiones: "10-12 rep", descanso: "75 s", notas: "Sin balanceo de tronco." },
          { nombre: "Fondos asistidos", series: 3, repeticiones: "8-12 rep", descanso: "75 s", notas: "Rango cómodo para hombro." },
          { nombre: "Jalón agarre neutro", series: 3, repeticiones: "10-12 rep", descanso: "75 s", notas: "Codos hacia costados." },
        ],
      },
      {
        dia: "dia_3",
        nombre_dia: "Día 3 · Pierna + Core",
        enfoque: "Pierna base y estabilidad",
        musculo: "Pierna",
        notas: "Mantén rango cómodo y control de respiración en básicos.",
        ejercicios: [
          { nombre: "Sentadilla trasera o multipower", series: 4, repeticiones: "6-8 rep", descanso: "120-150 s", notas: "Profundidad según movilidad." },
          { nombre: "Prensa inclinada", series: 3, repeticiones: "10-12 rep", descanso: "90 s", notas: "Empuja con planta completa." },
          { nombre: "Zancadas caminando", series: 3, repeticiones: "10-12 rep por pierna", descanso: "75-90 s", notas: "Paso largo, tronco estable." },
          { nombre: "Plancha frontal", series: 3, repeticiones: "30-45 s", descanso: "45 s", notas: "Respira sin perder alineación." },
        ],
      },
    ],
    recomendaciones_generales: [
      "Realiza 8-12 minutos de calentamiento dinámico y 1-2 series de aproximación del primer ejercicio.",
      "Trabaja con 1-3 repeticiones en reserva en la mayoría de series.",
      "Cuando completes el rango alto en todas las series, sube la carga entre 2% y 5%.",
      "Finaliza con 5-10 minutos de vuelta a la calma y respiración nasal.",
    ],
  },
  "plantilla-torso-pierna-4-dias": {
    id: "pdf-masa-principiante-torso-pierna-4d",
    slug: "masa-principiante-torso-pierna-4d",
    title: "Torso-Pierna Inicial (4 días)",
    short_description: "División clásica para subir volumen de entrenamiento sin exceso de fatiga.",
    level_label: "Principiante",
    objetivo: "ganar_masa_muscular",
    experiencia: "principiante",
    dias_por_semana: 4,
    duracion_semanas: 8,
    estimated_session_minutes: 65,
    focus_areas: ["torso-pierna", "progresión simple", "hipertrofia general"],
    dias: [
      { dia: "dia_1", nombre_dia: "Día 1 · Torso Empuje", enfoque: "Pecho, hombro, tríceps", musculo: "Torso", ejercicios: [{ nombre: "Press de banca", series: 4, repeticiones: "6-8 rep", descanso: "120 s" }, { nombre: "Press inclinado mancuernas", series: 3, repeticiones: "8-10 rep", descanso: "90 s" }, { nombre: "Press militar sentado", series: 3, repeticiones: "8-10 rep", descanso: "90 s" }, { nombre: "Elevaciones laterales", series: 3, repeticiones: "12-15 rep", descanso: "60 s" }] },
      { dia: "dia_2", nombre_dia: "Día 2 · Pierna Base", enfoque: "Cuádriceps y glúteo", musculo: "Pierna", ejercicios: [{ nombre: "Sentadilla", series: 4, repeticiones: "6-8 rep", descanso: "120-150 s" }, { nombre: "Prensa", series: 3, repeticiones: "10-12 rep", descanso: "90 s" }, { nombre: "Peso muerto rumano", series: 3, repeticiones: "8-10 rep", descanso: "120 s" }, { nombre: "Gemelos", series: 3, repeticiones: "12-15 rep", descanso: "60 s" }] },
      { dia: "dia_3", nombre_dia: "Día 3 · Torso Tracción", enfoque: "Espalda y bíceps", musculo: "Torso", ejercicios: [{ nombre: "Jalón al pecho", series: 4, repeticiones: "8-10 rep", descanso: "90 s" }, { nombre: "Remo con barra", series: 4, repeticiones: "6-10 rep", descanso: "90-120 s" }, { nombre: "Face pull", series: 3, repeticiones: "12-15 rep", descanso: "60 s" }, { nombre: "Curl barra Z", series: 3, repeticiones: "10-12 rep", descanso: "60 s" }] },
      { dia: "dia_4", nombre_dia: "Día 4 · Pierna Posterior", enfoque: "Cadena posterior y core", musculo: "Pierna", ejercicios: [{ nombre: "Hip thrust", series: 4, repeticiones: "8-10 rep", descanso: "90 s" }, { nombre: "Peso muerto barra hexagonal", series: 3, repeticiones: "5-8 rep", descanso: "120 s" }, { nombre: "Curl femoral", series: 3, repeticiones: "10-12 rep", descanso: "75 s" }, { nombre: "Pallof press", series: 3, repeticiones: "10-12 rep por lado", descanso: "45-60 s" }] },
    ],
    recomendaciones_generales: ["Prioriza técnica en básicos y deja el fallo solo para la última serie de accesorios.", "Si acumulaste demasiada fatiga de pierna, baja 1-2 series en día 4.", "Mantén 1-2 días de cardio suave de 20-30 minutos."],
  },
  "plan-ppl-5-dias": {
    id: "pdf-masa-intermedio-ppl-5d",
    slug: "masa-intermedio-ppl-5d",
    title: "Hipertrofia Push Pull Legs + Extra (5 días)",
    short_description: "Estructura PPL con día adicional para rezagos y volumen de calidad.",
    level_label: "Intermedio",
    objetivo: "ganar_masa_muscular",
    experiencia: "intermedio",
    dias_por_semana: 5,
    duracion_semanas: 10,
    estimated_session_minutes: 75,
    focus_areas: ["PPL", "volumen alto", "músculos rezagados"],
    dias: [
      { dia: "dia_1", nombre_dia: "Día 1 · Push", enfoque: "Empuje", musculo: "Torso", ejercicios: [{ nombre: "Press banca", series: 4, repeticiones: "6-8 rep", descanso: "120 s" }, { nombre: "Press inclinado", series: 3, repeticiones: "8-10 rep", descanso: "90 s" }, { nombre: "Elevaciones laterales", series: 3, repeticiones: "12-15 rep", descanso: "60 s" }] },
      { dia: "dia_2", nombre_dia: "Día 2 · Pull", enfoque: "Tracción", musculo: "Espalda", ejercicios: [{ nombre: "Jalón al pecho", series: 4, repeticiones: "8-10 rep", descanso: "90 s" }, { nombre: "Remo barra", series: 4, repeticiones: "6-10 rep", descanso: "90-120 s" }, { nombre: "Curl barra Z", series: 3, repeticiones: "10-12 rep", descanso: "60 s" }] },
      { dia: "dia_3", nombre_dia: "Día 3 · Legs", enfoque: "Pierna", musculo: "Pierna", ejercicios: [{ nombre: "Sentadilla", series: 4, repeticiones: "6-8 rep", descanso: "120-150 s" }, { nombre: "Prensa", series: 3, repeticiones: "10-12 rep", descanso: "90 s" }, { nombre: "Peso muerto rumano", series: 3, repeticiones: "8-10 rep", descanso: "120 s" }] },
      { dia: "dia_4", nombre_dia: "Día 4 · Torso Mixto", enfoque: "Volumen complementario", musculo: "Torso", ejercicios: [{ nombre: "Press máquina", series: 3, repeticiones: "10-12 rep", descanso: "75 s" }, { nombre: "Remo pecho apoyado", series: 3, repeticiones: "10-12 rep", descanso: "75 s" }, { nombre: "Fondos asistidos", series: 3, repeticiones: "8-12 rep", descanso: "75 s" }] },
      { dia: "dia_5", nombre_dia: "Día 5 · Pierna Posterior + Core", enfoque: "Posterior", musculo: "Pierna", ejercicios: [{ nombre: "Hip thrust", series: 4, repeticiones: "8-10 rep", descanso: "90 s" }, { nombre: "Sentadilla búlgara", series: 3, repeticiones: "8-10 rep por pierna", descanso: "90 s" }, { nombre: "Pallof press", series: 3, repeticiones: "10-12 rep por lado", descanso: "45-60 s" }] },
    ],
    recomendaciones_generales: ["Día 4 y 5 se pueden alternar según recuperación de pierna.", "Si no duermes al menos 7h, evita subir carga esa semana.", "Haz descarga del 25% de volumen cada 5-6 semanas."],
  },
}
