import type { Metadata, Viewport } from "next"
import { Space_Grotesk, Inter } from "next/font/google"
import { siteConfig, developerConfig } from "@/config/site"
import { ThemeProvider } from "@/components/layout/ThemeProvider"
import { Toaster } from "@/components/ui/sonner"
import { GoogleAdSense } from "@/components/ads/GoogleAdSense"
import "./globals.css"

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
})

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-space-grotesk",
  display: "swap",
})

export const viewport: Viewport = {
  themeColor: "#0A0A0B",
}

// Google AdSense site verification — rendered server-side in <head>.
// meta name="google-adsense-account" is the method required by AdSense to confirm ownership.
// The actual ad SDK is loaded by <GoogleAdSense /> in <body> (future ad infrastructure).
const adsenseClientId = process.env.NEXT_PUBLIC_ADSENSE_CLIENT_ID

// OG image is generated by src/app/opengraph-image.tsx (1200×630, edge runtime).
// Next.js auto-discovers it as og:image + twitter:image — no manual images entry needed.
export const metadata: Metadata = {
  metadataBase: new URL(siteConfig.url),
  title: {
    default: `${siteConfig.name} — ${siteConfig.slogan}`,
    template: `%s | ${siteConfig.name}`,
  },
  description: siteConfig.description,
  applicationName: siteConfig.name,
  creator: developerConfig.name,
  publisher: siteConfig.name,
  manifest: "/manifest.webmanifest",
  // favicon.ico, icon.png and apple-icon.png in /app are auto-detected
  // by Next.js file-based metadata — no manual icon entries needed here.
  appleWebApp: {
    capable: true,
    title: siteConfig.name,
    statusBarStyle: "black-translucent",
  },
  alternates: {
    canonical: siteConfig.url,
  },
  openGraph: {
    type: "website",
    siteName: siteConfig.name,
    locale: "es_MX",
    url: siteConfig.url,
    title: `${siteConfig.name} — ${siteConfig.slogan}`,
    description: siteConfig.description,
    // images auto-populated from opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
    title: `${siteConfig.name} — ${siteConfig.slogan}`,
    description: siteConfig.description,
    // images auto-populated from opengraph-image.tsx
  },
  // AdSense ownership verification — emits <meta name="google-adsense-account" content="ca-pub-...">
  // server-rendered in <head> without JS dependency.
  ...(adsenseClientId
    ? { other: { "google-adsense-account": adsenseClientId } }
    : {}),
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="es"
      className={`h-full antialiased ${inter.variable} ${spaceGrotesk.variable}`}
      suppressHydrationWarning
    >
      <body className="flex min-h-full flex-col">
        <ThemeProvider>{children}</ThemeProvider>
        <Toaster />
        <GoogleAdSense />
      </body>
    </html>
  )
}
